// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetHandValue
int GetHandValue(IntegerVector cards, IntegerVector HR);
RcppExport SEXP pokeR_GetHandValue(SEXP cardsSEXP, SEXP HRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type cards(cardsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type HR(HRSEXP);
    __result = Rcpp::wrap(GetHandValue(cards, HR));
    return __result;
END_RCPP
}
// GetMultiHandValue
IntegerVector GetMultiHandValue(IntegerVector multicards, IntegerVector HR);
RcppExport SEXP pokeR_GetMultiHandValue(SEXP multicardsSEXP, SEXP HRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type multicards(multicardsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type HR(HRSEXP);
    __result = Rcpp::wrap(GetMultiHandValue(multicards, HR));
    return __result;
END_RCPP
}
// GetMultiHandValueSpecialK
IntegerVector GetMultiHandValueSpecialK(IntegerVector multicards);
RcppExport SEXP pokeR_GetMultiHandValueSpecialK(SEXP multicardsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type multicards(multicardsSEXP);
    __result = Rcpp::wrap(GetMultiHandValueSpecialK(multicards));
    return __result;
END_RCPP
}
