# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetHandValue <- function(cards, HR) {
    .Call('pokeR_GetHandValue', PACKAGE = 'pokeR', cards, HR)
}

GetMultiHandValue <- function(multicards, HR) {
    .Call('pokeR_GetMultiHandValue', PACKAGE = 'pokeR', multicards, HR)
}

GetMultiHandValueSpecialK <- function(multicards) {
    .Call('pokeR_GetMultiHandValueSpecialK', PACKAGE = 'pokeR', multicards)
}

